### ISSUE TITLE
Can't run the development server

### ISSUE THREAD

**Issue by rixcian** [lensterxyz/lenster#3150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I ran `pnpm dev`, but this error occurred:

```
@workers/sts-generator:dev: /home/rkremecek/projects/personal/lenster/node_modules/.pnpm/wrangler@3.1.0/node_modules/wrangler/wrangler-dist/cli.js:30632
@workers/sts-generator:dev:             throw a;
@workers/sts-generator:dev:             ^
@workers/sts-generator:dev: 
@workers/sts-generator:dev: Error: write EPIPE
@workers/sts-generator:dev:     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
@workers/sts-generator:dev:     at writeGeneric (node:internal/stream_base_commons:151:3)
@workers/sts-generator:dev:     at Socket._writeGeneric (node:net:930:11)
@workers/sts-generator:dev:     at Socket._write (node:net:942:8)
@workers/sts-generator:dev:     at writeOrBuffer (node:internal/streams/writable:392:12)
@workers/sts-generator:dev:     at _write (node:internal/streams/writable:333:10)
@workers/sts-generator:dev:     at Writable.write (node:internal/streams/writable:337:10)
@workers/sts-generator:dev:     at Runtime.updateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:5121:26)
@workers/sts-generator:dev:     at async #assembleAndUpdateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:9138:23)
@workers/sts-generator:dev:     at async #init (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:8898:5)
@workers/sts-generator:dev: Emitted 'error' event on Socket instance at:
@workers/sts-generator:dev:     at emitErrorNT (node:internal/streams/destroy:151:8)
@workers/sts-generator:dev:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
@workers/sts-generator:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
@workers/sts-generator:dev:   errno: -32,
@workers/sts-generator:dev:   code: 'EPIPE',
@workers/sts-generator:dev:   syscall: 'write'
@workers/sts-generator:dev: }
@workers/sts-generator:dev: 
@workers/sts-generator:dev: Node.js v18.15.0
@workers/sts-generator:dev:  ELIFECYCLE  Command failed with exit code 7.
@workers/freshdesk:dev: ✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
@workers/freshdesk:dev: 

@workers/spaces:dev: ▲ [WARNING] Enabling Node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.
@workers/spaces:dev: 
@workers/spaces:dev: 
@workers/leafwatch:dev: ⎔ Starting local server...
@workers/leafwatch:dev: 
@workers/oembed:dev: ⎔ Starting local server...
@workers/oembed:dev: 
@workers/ens-resolver:dev: ⎔ Starting local server...
@workers/ens-resolver:dev: 
@workers/leafwatch:dev: /home/rkremecek/projects/personal/lenster/node_modules/.pnpm/@cloudflare+workerd-linux-64@1.20230518.0/node_modules/@cloudflare/workerd-linux-64/bin/workerd: error while loading share

@workers/leafwatch:dev: ✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
@workers/leafwatch:dev: 

@workers/oembed:dev: /home/rkremecek/projects/personal/lenster/node_modules/.pnpm/wrangler@3.1.0/node_modules/wrangler/wrangler-dist/cli.js:30632
@workers/oembed:dev:             throw a;
@workers/oembed:dev:             ^
@workers/oembed:dev: 
@workers/oembed:dev: Error: write EPIPE
@workers/oembed:dev:     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
@workers/oembed:dev:     at writeGeneric (node:internal/stream_base_commons:151:3)
@workers/oembed:dev:     at Socket._writeGeneric (node:net:930:11)
@workers/oembed:dev:     at Socket._write (node:net:942:8)
@workers/oembed:dev:     at writeOrBuffer (node:internal/streams/writable:392:12)
@workers/oembed:dev:     at _write (node:internal/streams/writable:333:10)
@workers/oembed:dev:     at Writable.write (node:internal/streams/writable:337:10)
@workers/oembed:dev:     at Runtime.updateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:5121:26)
@workers/oembed:dev:     at async #assembleAndUpdateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:9138:23)
@workers/oembed:dev:     at async #init (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:8898:5)
@workers/oembed:dev: Emitted 'error' event on Socket instance at:
@workers/oembed:dev:     at emitErrorNT (node:internal/streams/destroy:151:8)
@workers/oembed:dev:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
@workers/oembed:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
@workers/oembed:dev:   errno: -32,
@workers/oembed:dev:   code: 'EPIPE',
@workers/oembed:dev:   syscall: 'write'
@workers/oembed:dev: }
@workers/oembed:dev: 
@workers/oembed:dev: Node.js v18.15.0
@workers/oembed:dev:  ELIFECYCLE  Command failed with exit code 7.
@workers/snapshot-relay:dev: ⎔ Starting local server...
@workers/snapshot-relay:dev: 
@workers/ens-resolver:dev: /home/rkremecek/projects/personal/lenster/node_modules/.pnpm/wrangler@3.1.0/node_modules/wrangler/wrangler-dist/cli.js:30632
@workers/ens-resolver:dev:             throw a;
@workers/ens-resolver:dev:             ^
@workers/ens-resolver:dev: 
@workers/ens-resolver:dev: Error: write EPIPE
@workers/ens-resolver:dev:     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
@workers/ens-resolver:dev:     at writeGeneric (node:internal/stream_base_commons:151:3)
@workers/ens-resolver:dev:     at Socket._writeGeneric (node:net:930:11)
@workers/ens-resolver:dev:     at Socket._write (node:net:942:8)
@workers/ens-resolver:dev:     at writeOrBuffer (node:internal/streams/writable:392:12)
@workers/ens-resolver:dev:     at _write (node:internal/streams/writable:333:10)
@workers/ens-resolver:dev:     at Writable.write (node:internal/streams/writable:337:10)
@workers/ens-resolver:dev:     at Runtime.updateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:5121:26)
@workers/ens-resolver:dev:     at async #assembleAndUpdateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:9138:23)
@workers/ens-resolver:dev:     at async #init (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:8898:5)
@workers/ens-resolver:dev: Emitted 'error' event on Socket instance at:
@workers/ens-resolver:dev:     at emitErrorNT (node:internal/streams/destroy:151:8)
@workers/ens-resolver:dev:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
@workers/ens-resolver:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
@workers/ens-resolver:dev:   errno: -32,
@workers/ens-resolver:dev:   code: 'EPIPE',
@workers/ens-resolver:dev:   syscall: 'write'
@workers/ens-resolver:dev: }
@workers/ens-resolver:dev: 
@workers/ens-resolver:dev: Node.js v18.15.0
@workers/spaces:dev: ⎔ Starting local server...
@workers/spaces:dev: 
@workers/ens-resolver:dev:  ELIFECYCLE  Command failed with exit code 7.
@workers/metadata:dev: ⎔ Starting local server...
@workers/metadata:dev: 
@workers/spaces:dev: /home/rkremecek/projects/personal/lenster/node_modules/.pnpm/wrangler@3.1.0/node_modules/wrangler/wrangler-dist/cli.js:30632
@workers/spaces:dev:             throw a;
@workers/spaces:dev:             ^
@workers/spaces:dev: 
@workers/spaces:dev: Error: write EPIPE
@workers/spaces:dev:     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
@workers/spaces:dev:     at writeGeneric (node:internal/stream_base_commons:151:3)
@workers/spaces:dev:     at Socket._writeGeneric (node:net:930:11)
@workers/spaces:dev:     at Socket._write (node:net:942:8)
@workers/spaces:dev:     at writeOrBuffer (node:internal/streams/writable:392:12)
@workers/spaces:dev:     at _write (node:internal/streams/writable:333:10)
@workers/spaces:dev:     at Writable.write (node:internal/streams/writable:337:10)
@workers/spaces:dev:     at Runtime.updateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:5121:26)
@workers/spaces:dev:     at async #assembleAndUpdateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:9138:23)
@workers/spaces:dev:     at async #init (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:8898:5)
@workers/spaces:dev: Emitted 'error' event on Socket instance at:
@workers/spaces:dev:     at emitErrorNT (node:internal/streams/destroy:151:8)
@workers/spaces:dev:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
@workers/spaces:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
@workers/spaces:dev:   errno: -32,
@workers/spaces:dev:   code: 'EPIPE',
@workers/spaces:dev:   syscall: 'write'
@workers/spaces:dev: }
@workers/spaces:dev: 
@workers/spaces:dev: Node.js v18.15.0
@workers/snapshot-relay:dev: /home/rkremecek/projects/personal/lenster/node_modules/.pnpm/wrangler@3.1.0/node_modules/wrangler/wrangler-dist/cli.js:30632
@workers/snapshot-relay:dev:             throw a;
@workers/snapshot-relay:dev:             ^
@workers/snapshot-relay:dev: 
@workers/snapshot-relay:dev: Error: write EPIPE
@workers/snapshot-relay:dev:     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
@workers/snapshot-relay:dev:     at writeGeneric (node:internal/stream_base_commons:151:3)
@workers/snapshot-relay:dev:     at Socket._writeGeneric (node:net:930:11)
@workers/snapshot-relay:dev:     at Socket._write (node:net:942:8)
@workers/snapshot-relay:dev:     at writeOrBuffer (node:internal/streams/writable:392:12)
@workers/snapshot-relay:dev:     at _write (node:internal/streams/writable:333:10)
@workers/snapshot-relay:dev:     at Writable.write (node:internal/streams/writable:337:10)
@workers/snapshot-relay:dev:     at Runtime.updateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:5121:26)
@workers/snapshot-relay:dev:     at async #assembleAndUpdateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:9138:23)
@workers/snapshot-relay:dev:     at async #init (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:8898:5)
@workers/snapshot-relay:dev: Emitted 'error' event on Socket instance at:
@workers/snapshot-relay:dev:     at emitErrorNT (node:internal/streams/destroy:151:8)
@workers/snapshot-relay:dev:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
@workers/snapshot-relay:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
@workers/snapshot-relay:dev:   errno: -32,
@workers/snapshot-relay:dev:   code: 'EPIPE',
@workers/snapshot-relay:dev:   syscall: 'write'
@workers/snapshot-relay:dev: }
@workers/snapshot-relay:dev: 
@workers/snapshot-relay:dev: Node.js v18.15.0
@workers/spaces:dev:  ELIFECYCLE  Command failed with exit code 7.
@workers/snapshot-relay:dev:  ELIFECYCLE  Command failed with exit code 7.
@lenster/web:dev: Done!
@workers/metadata:dev: /home/rkremecek/projects/personal/lenster/node_modules/.pnpm/wrangler@3.1.0/node_modules/wrangler/wrangler-dist/cli.js:30632
@workers/metadata:dev:             throw a;
@workers/metadata:dev:             ^
@workers/metadata:dev: 
@workers/metadata:dev: Error: write EPIPE
@workers/metadata:dev:     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
@workers/metadata:dev:     at writeGeneric (node:internal/stream_base_commons:151:3)
@workers/metadata:dev:     at Socket._writeGeneric (node:net:930:11)
@workers/metadata:dev:     at Socket._write (node:net:942:8)
@workers/metadata:dev:     at writeOrBuffer (node:internal/streams/writable:392:12)
@workers/metadata:dev:     at _write (node:internal/streams/writable:333:10)
@workers/metadata:dev:     at Writable.write (node:internal/streams/writable:337:10)
@workers/metadata:dev:     at Runtime.updateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:5121:26)
@workers/metadata:dev:     at async #assembleAndUpdateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:9138:23)
@workers/metadata:dev:     at async #init (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:8898:5)
@workers/metadata:dev: Emitted 'error' event on Socket instance at:
@workers/metadata:dev:     at emitErrorNT (node:internal/streams/destroy:151:8)
@workers/metadata:dev:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
@workers/metadata:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
@workers/metadata:dev:   errno: -32,
@workers/metadata:dev:   code: 'EPIPE',
@workers/metadata:dev:   syscall: 'write'
@workers/metadata:dev: }
@workers/metadata:dev: 
@workers/metadata:dev: Node.js v18.15.0
@workers/metadata:dev:  ELIFECYCLE  Command failed with exit code 7.
@workers/snapshot-relay:dev: ERROR: command finished with error: command (/home/rkremecek/projects/personal/lenster/packages/workers/snapshot-relay) pnpm run dev exited (1)
@workers/freshdesk:dev: ⎔ Shutting down local server...
@workers/leafwatch:dev: ⎔ Shutting down local server...
@lenster/web:dev:  ELIFECYCLE  Command failed.
@workers/freshdesk:dev:  ELIFECYCLE  Command failed.
@workers/leafwatch:dev:  ELIFECYCLE  Command failed.
@lenster/prerender:dev:  ELIFECYCLE  Command failed.
command (/home/rkremecek/projects/personal/lenster/packages/workers/snapshot-relay) pnpm run dev exited (1)

 Tasks:    0 successful, 10 total
Cached:    0 cached, 10 total
  Time:    2.803s 
Failed:    @workers/snapshot-relay#dev

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected Behavior

Start the development server.

### Steps To Reproduce

- `pnpm install`
- `pnpm dev`

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Others

### Anything else?

Node.js version: `18.15`
PNPM version: `8.5.0`
OS: `Ubuntu 20.04 LTS`

**Comment by rixcian** [comment]
@foolo Thanks for the solution <3 

Unfortunately, the `ens-resolver` worker still returns the same error (other services seem to be fixed)...

```
@workers/ens-resolver:dev:  ⛅️ wrangler 3.1.0 (update available 3.1.1)
@workers/ens-resolver:dev: -------------------------------------------
@workers/ens-resolver:dev: wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
@workers/ens-resolver:dev: To run an edge preview session for your Worker, use wrangler dev --remote
@workers/ens-resolver:dev: ⎔ Starting local server...
@workers/ens-resolver:dev: 
@workers/ens-resolver:dev: /home/rkremecek/projects/personal/lenster/node_modules/.pnpm/wrangler@3.1.0/node_modules/wrangler/wrangler-dist/cli.js:30632
@workers/ens-resolver:dev:             throw a;
@workers/ens-resolver:dev:             ^
@workers/ens-resolver:dev: 
@workers/ens-resolver:dev: Error: write EPIPE
@workers/ens-resolver:dev:     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
@workers/ens-resolver:dev:     at writeGeneric (node:internal/stream_base_commons:151:3)
@workers/ens-resolver:dev:     at Socket._writeGeneric (node:net:874:11)
@workers/ens-resolver:dev:     at Socket._write (node:net:886:8)
@workers/ens-resolver:dev:     at writeOrBuffer (node:internal/streams/writable:391:12)
@workers/ens-resolver:dev:     at _write (node:internal/streams/writable:332:10)
@workers/ens-resolver:dev:     at Socket.Writable.write (node:internal/streams/writable:336:10)
@workers/ens-resolver:dev:     at Runtime.updateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:5121:26)
@workers/ens-resolver:dev:     at async Miniflare.#assembleAndUpdateConfig (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:9138:23)
@workers/ens-resolver:dev:     at async Miniflare.#init (/home/rkremecek/projects/personal/lenster/node_modules/.pnpm/miniflare@3.0.1/node_modules/miniflare/dist/src/index.js:8898:5)
@workers/ens-resolver:dev: Emitted 'error' event on Socket instance at:
@workers/ens-resolver:dev:     at emitErrorNT (node:internal/streams/destroy:157:8)
@workers/ens-resolver:dev:     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
@workers/ens-resolver:dev:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
@workers/ens-resolver:dev:   errno: -32,
@workers/ens-resolver:dev:   code: 'EPIPE',
@workers/ens-resolver:dev:   syscall: 'write'
@workers/ens-resolver:dev: }
@workers/ens-resolver:dev:  ELIFECYCLE  Command failed with exit code 7.
@workers/ens-resolver:dev: ERROR: command finished with error: command (/home/rkremecek/projects/personal/lenster/packages/workers/ens-resolver) pnpm run dev exited (1)
@workers/leafwatch:dev:  ELIFECYCLE  Command failed.
@workers/oembed:dev:  ELIFECYCLE  Command failed.
@workers/sts-generator:dev:  ELIFECYCLE  Command failed.
@workers/spaces:dev:  ELIFECYCLE  Command failed.
@workers/freshdesk:dev:  ELIFECYCLE  Command failed.
@workers/snapshot-relay:dev:  ELIFECYCLE  Command failed.
@workers/metadata:dev:  ELIFECYCLE  Command failed.
@lenster/prerender:dev:  ELIFECYCLE  Command failed.
@lenster/web:dev:  ELIFECYCLE  Command failed.
command (/home/rkremecek/projects/personal/lenster/packages/workers/ens-resolver) pnpm run dev exited (1)

 Tasks:    0 successful, 10 total
Cached:    0 cached, 10 total
  Time:    5.706s 
Failed:    @workers/ens-resolver#dev

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by foolo** [comment]
@rixcian Ahh, now I see that you are using Ubuntu version 20 and not 22 (Sorry, for some reason I mixed it up) . The solution apparently only works for Ubuntu 22. Unfortunately they don't mention any working solution for Ubuntu 20.

**Comment by bigint** [comment]
Is this still a thing?

**Comment by foolo** [comment]
> Is this still a thing?

@bigint  I think we can close this, since it works on Ubuntu 22 with the above fix (`sudo apt-get install libc++1`). I don't think it's necessary to support Ubuntu 20.

**Comment by bigint** [comment]
Cool
