### ISSUE TITLE
Bad request for relevant profiles section

### ISSUE THREAD

**Issue by donosonaumczuk** [lensterxyz/lenster#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It doesn't happen in all posts

### Expected Behavior

Returning 2XX instead of 400

### Steps To Reproduce

See the following post:
https://lenster.xyz/posts/0xbff7-0x13

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

### Anything else?

![image](https://user-images.githubusercontent.com/23125060/184661671-78ea420a-f2d1-48bf-a1cd-ae76e045613b.png)
---
Request:
```
{"operationName":"RelevantPeople","variables":{"request":{"handles":["santicristobal.lens","lensprotocol","donosonaumczuk?"]}},"query":"query RelevantPeople($request: ProfileQueryRequest!) {\n  profiles(request: $request) {\n    items {\n      ...MinimalProfileFields\n      isFollowedByMe\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment MinimalProfileFields on Profile {\n  id\n  name\n  handle\n  bio\n  ownedBy\n  attributes {\n    key\n    value\n    __typename\n  }\n  picture {\n    ... on MediaSet {\n      original {\n        url\n        __typename\n      }\n      __typename\n    }\n    ... on NftImage {\n      uri\n      __typename\n    }\n    __typename\n  }\n  followModule {\n    __typename\n  }\n  __typename\n}"}
```
---
Response:
```
{"errors":[{"message":"Variable \"$request\" got invalid value \"donosonaumczuk?\" at \"request.handles[2]\"; Expected type \"Handle\". Handle only supports lower case characters, numbers, - and _. Handle must be minimum of 5 length and maximum of 31 length - donosonaumczuk?","locations":[{"line":1,"column":22}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["ValidationError: Handle only supports lower case characters, numbers, - and _. Handle must be minimum of 5 length and maximum of 31 length - donosonaumczuk?","    at Handle.validate (/usr/src/app/packages/api-lens-custom-types/lib/handle.type.js:20:19)","    at new BaseType (/usr/src/app/packages/custom-types-shared/lib/base-types/base-type.js:9:14)","    at new StringType (/usr/src/app/packages/custom-types-shared/lib/base-types/string.type.js:9:9)","    at new Handle (/usr/src/app/packages/api-lens-custom-types/lib/handle.type.js:10:9)","    at GraphQLScalarType.parseValue (/usr/src/app/packages/api-lens/lib/graphql/scalars/handle.scalar.js:16:16)","    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:128:26)","    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:54:14)","    at /usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:70:14","    at Array.map (<anonymous>)","    at safeArrayFrom (/usr/src/app/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)"]}}}]}
```

**Comment by bigint** [comment]
Thanks for raising this @donosonaumczuk 🙏🏼 

Fix on the way 🚀

**Comment by bigint** [comment]
Fixed 🚀 

Deploying :shipit:
